wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: valid_0_binary_logloss
      6:
      - 3
      7:
      - 1
    python_version: 3.8.8
    start_time: 1672954465.585328
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 25
      - 37
      4: 3.8.8
      5: 0.13.6
      8:
      - 1
      - 5
boosting_type:
  desc: null
  value: gbdt
colsample_bytree:
  desc: null
  value: 0.5052766008097228
early_stopping_round:
  desc: null
  value: 20
early_stopping_rounds:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.01
max_depth:
  desc: null
  value: -1
metric:
  desc: null
  value:
  - binary
min_child_samples:
  desc: null
  value: 20
min_child_weight:
  desc: null
  value: 0.001
min_split_gain:
  desc: null
  value: 0.0
n_jobs:
  desc: null
  value: -1
num_iterations:
  desc: null
  value: 100
num_leaves:
  desc: null
  value: 69
objective:
  desc: null
  value: binary
random_state:
  desc: null
  value: null
reg_alpha:
  desc: null
  value: 0.0
reg_lambda:
  desc: null
  value: 0.0
subsample:
  desc: null
  value: 0.9519071518722312
subsample_for_bin:
  desc: null
  value: 200000
subsample_freq:
  desc: null
  value: 0
verbose:
  desc: null
  value: -1
