wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: valid_0_auc
      6:
      - 3
      7:
      - 2
    python_version: 3.8.8
    start_time: 1672954258.945094
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 53
      - 55
      3:
      - 2
      - 7
      - 23
      - 25
      - 37
      4: 3.8.8
      5: 0.13.6
      8:
      - 1
      - 5
boosting_type:
  desc: null
  value: gbdt
colsample_bytree:
  desc: null
  value: 0.8171291347820884
early_stopping_round:
  desc: null
  value: 5
early_stopping_rounds:
  desc: null
  value: 40
learning_rate:
  desc: null
  value: 0.01
max_depth:
  desc: null
  value: -1
metric:
  desc: null
  value:
  - auc
min_child_samples:
  desc: null
  value: 20
min_child_weight:
  desc: null
  value: 0.001
min_split_gain:
  desc: null
  value: 0.0
n_jobs:
  desc: null
  value: -1
num_iterations:
  desc: null
  value: 100
num_leaves:
  desc: null
  value: 79
num_threads:
  desc: null
  value: 10
objective:
  desc: null
  value: binary
random_state:
  desc: null
  value: 42
reg_alpha:
  desc: null
  value: 1
reg_lambda:
  desc: null
  value: 0.0
subsample:
  desc: null
  value: 0.6269308005049522
subsample_for_bin:
  desc: null
  value: 200000
subsample_freq:
  desc: null
  value: 0
verbosity:
  desc: null
  value: -1
