wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1672954512.501263
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 55
      2:
      - 1
      - 5
      - 8
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.8.8
      5: 0.13.6
      8:
      - 1
      - 5
colsample_bytree:
  desc: null
  value: 0.11470845996099308
early_stopping_rounds:
  desc: null
  value: 20
num_leaves:
  desc: null
  value: 48
subsample:
  desc: null
  value: 0.9036315396970092
