wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1672891917.614256
    t:
      1:
      - 1
      - 5
      - 8
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.8
      5: 0.13.6
      8:
      - 1
      - 5
wandb_nb:
  desc: null
  value: wandb_stopAndFrisk
